name: 'Release Edgee CLI to Homebrew'
description: 'Update the edgee-cloud/homebrew-edgee repository with the latest release of Edgee CLI to Homebrew'
inputs:
  ACTION_GH_TOKEN: 
     description: "The GitHub Token used to push and create a new PR"
     required: true
runs:
  using: "composite"
  steps:
    # check out this repo
    - uses: actions/checkout@v4
      with:
          repository: edgee-cloud/homebrew-edgee
          ref: gh-action-automation
          path: 'homebrew-edgee'

    # create and update local files
    - name: Update files, commit, push, and open PR
      shell: bash
      working-directory: homebrew-edgee
      env:
          GH_TOKEN: ${{ inputs.ACTION_GH_TOKEN }}
      run: |
        echo "::group::new-version.sh"
        bash new-version.sh
        echo "::endgroup::"
